name: Build (Desktop)
on: [push, pull_request]

jobs:
  build-desktop:
    runs-on: windows-latest
    env:
      VisualStudioVersion: '16.0'

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: galactic
    - uses: ros-tooling/action-ros-ci@0.2.4
      with:
        package-name: rcldotnet_examples
        target-ros2-distro: galactic
        vcs-repo-file-url: ${{github.workspace}}/.github/workflows/ci.repos
        extra-cmake-args: -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -Wno-dev